### ISSUE TITLE
Freezing at "Processing" screen on Nano S

### ISSUE THREAD

**Issue by aido** [LedgerHQ/app-recovery-check#15]
Hi,

The version of app-recovery-check available for Nano S on Ledger Live is v1.0.7. This works just fine; when I input my BIP39 phrase I get a `*Processing` screen for a couple of seconds then my phrase is shown as valid.

However, if I build app-recovery-check and sideload it onto a Nano S device the app freezes at the `*Processing` screen. When tested with Speculos the app does not freeze, it only happens on the physical device.

I have built and sideloaded several versions of the app, (including version 1.0.7) using several versions of nanos-secure-sdk. All with the same result, a freeze.

When sideloading onto the device I have also tried several values for `--appFlags`. Again, all freeze.

One possible reason for this strange behaviour is that when sideloading onto the device the app needs a certain value for `--appFlags` . I have tried `0x210` as in the v1.0,7 Makefile,  `0x10` as used in more recent versions of the Makefile, I even used `0x2F0`! All resulting in the same freeze. 

So, is there a value for `--appFlags` that will cause the app to **not** freeze when sideloaded onto a device? And if the value of `--appFlags` is not the cause of this issue then what is the cause?

Also, this only seems to happen with valid, matching BIP39 phrases. If a phrase is invalid or does not match with the device's seed then the app does not freeze.

> [!NOTE]  
> I have written my own app which is based on a fork of app-recovery-check and I am facing the same issue.

**Comment by lpascal-ledger** [comment]
Hey!

Good catch, thanks for that!
Indeed a bug creeped in the app more than one year ago. [This](https://github.com/LedgerHQ/app-recovery-check/commit/b9e0928a3341c47cdc8d91fb8b0497d7b43ff92f#diff-af64ca1c44f31e6a184ebcdc5f55513a65e12c408485e41e5666b1d70d06a806L338) is the error: those `os_derive_bip32*` functions cannot take `NULL` path apparently (even with size of 0).

I've pushed a fix in #16, I hope that'll also make your app work!

Thanks again for the debunk!
