### ISSUE TITLE
make the texts identical on Nano S and X

### ISSUE THREAD

**Issue by My1** [LedgerHQ/app-recovery-check#2]
considering the recent rise in scams there is a lot of insecurity considering whether or not something is legit especially something as important as the recov check and if the output deviates from the tutorial video it kinda doesnt help.

https://www.reddit.com/r/ledgerwallet/comments/hcw5l0/recovery_phrase_check_ledger_x/

https://github.com/LedgerHQ/app-recovery-check/blob/master/src/nanos_enter_phrase.c#L76

https://github.com/LedgerHQ/app-recovery-check/blob/master/src/nanox_enter_phrase.c#L78

**Comment by TamtamHero** [comment]
Thanks for pointing it out, I just pushed an update of both S & X apps to display the same text.
https://github.com/LedgerHQ/app-recovery-check/commit/cc434a32674802bca5a7650cb462d3086573e4af
The tutorial has been updated and the video will be remade soon: https://support.ledger.com/hc/en-us/articles/360007223753-Recovery-Check
