### ISSUE TITLE
Building a Ledger App Used To Memorize the 24 Words

### ISSUE THREAD

**Issue by johnshearing** [LedgerHQ/app-recovery-check#4]
Greetings All,
I am the co-creator of the free and open source www.privatekeyvault.com
Now I want to address the biggest unsolved problem with the ledger Nano S and X.
The problem is that you need a secure location to keep your 24 words and most of the people on the planet do not have this.
So they keep their 24 words hidden as best they can.
More likely they don't use a Ledger device at all because they know that they can not keep their 24 words secure.
I want to make a Ledger app similar to an app already built.
This is of course your app (app-recovery-check) found right here:
I will start by making a fork of this repository.
The difference is that the app will read back your 24 words so you can practice memorizing them without ever having to write the words down.
Humans have been practicing memory techniques since ancient times.
Just google the phrase "Memory Palace".
Modern people have forgotten these techniques but now we need them again.
The application I want to build will make it possible apply and practice the Memory Palace technique on the 24 words without ever needing to write the words down.
I believe this will make it possible for those people without a secure place to store the 24 words to memorize them.
I want to discuss this with the community and I want help building the App if no one with more experience wants to do it.
How shall I proceed?
Much thanks

**Comment by lpascal-ledger** [comment]
This sounds like a Recover feature, or (in a less Ledger-corporate fashion) a [`app-seed-tool`](https://github.com/aido/app-seed-tool) feature (see the SSKR bit).
